### PR TITLE
Remove mehtod `convert_to_csv` from  CEAP dataset

### PR DESCRIPTION
**Pull request by lipemorais**
**What is the purpose of this Pull Request?**
The purpose is remove unnecessary method of CEAP dataset to make it cleaner.

**What was done to achieve this purpose?**
I just removed the method and checked if Rosie do not use this method anymore.

**How to test if it really works?**
Just running unit test you will able to see that nothing breaks in Serenata Toolbox.

**Who can help reviewing it?**
@jtemporal @anaschwendler could help with Rosie's knowledge.

### CODE REVIEW

**Comment by jtemporal** [comment]
Hey @lipemorais you are totally right! I'll make a PR to remove the method call from Rosie and as soon as that get merged I'll come back and merge this one 😉

PS.: intended version bump?

**Comment by jtemporal** [comment]
as mentioned before: [new PR opened](https://github.com/datasciencebr/rosie/pull/71)

**Comment by lipemorais** [comment]
It's updated and bumped! Just be careful with Rosie ;)

**Comment by lipemorais** [comment]
Since [denpendent PR](https://github.com/datasciencebr/rosie/pull/71) is already merged in [Rosie](https://github.com/datasciencebr/rosie/). I think that this is ready to be merged. @jtemporal @cuducos

**Pull request merged**
