### PR TITLE
Refactor deputies dataset tests

### PR DESCRIPTION
**Pull request by anaschwendler**
**What is the purpose of this Pull Request?**
Since yesterday we've been needing some fixes in our tests. @cuducos has fixed the `asyncio` tests in #162 and another little bug has appeared with the sets of tests in deputies dataset order. This PR fix that error.

**What was done to achieve this purpose?**
Basically we refactored the lists to sets structure, so its order don't matter, since the problem was that the order was inverted.

**How to test if it really works?**
Run the tests:
```console
$ pip install pytest pytest-cov
$ pytest
```

**Who can help reviewing it?**
@cuducos

### CODE REVIEW

**Comment by cuducos** [comment]
I wouldn't call it a minor version bump, just a micro. From `README.md`:

    MICRO: the API is the same, no risk of breaking code
    MINOR: values have been added, existing values are unchanged
    MAJOR: existing values have been changed or removed

By refactoring the tests the public API is exactly the same, no risk of breaking code. Yet no new values added and existing values are unchanged. What do you think?

**Comment by anaschwendler** [comment]
> By refactoring the tests the public API is exactly the same, no risk of breaking code. Yet no new values added and existing values are unchanged. What do you think?

I agree, I just didn't knew which one to change, nothing was added its true, I'll change that ;)

**Comment by cuducos** [comment]
> I just didn't knew which one to change

Feel free to suggest something different for that bit of the `README.md` if you have enhancements ideas ; )

**Comment by cuducos** [comment]
Yay :tada:

1. Brought the branch to my local environment:

```
$ git fetch origin && git checkout -b anaschwendler-refactor-deputies-dataset-tests origin/anaschwendler-refactor-deputies-dataset-tests
```

2. Ran unit tests:

```
$ pytest tests/unit
```

**Pull request merged**
