### PR TITLE
Add cities dataset to latest datasets download list

### LINKED ISSUE #78: Update Brazilian Cities CSV on the latest_backup list.
We are expanding our project to cities, in order to it we must update our dataset list.

We need to add the `2017-05-22-brazilian-cities.csv` to the `latest-backup` script, in order to make the `serenata-de_amor` notebooks work.

### PR DESCRIPTION
**Pull request by cuducos**
Fix #78

### CODE REVIEW

**Comment by cuducos** [comment]
```
def TestLatest(TestCase):

    def test_cities_was_added(self):
        self.assertIn('2017-05-22-brazilian-cities.csv', Datasets().downloader.LATEST)
```

Or even:

```
    def test_latest(self):
        self.assertEqual(28, len(Datasets().downloader.LATEST))
```

But the real question is would it worth it?

**Comment by lipemorais** [comment]
I don't think that this kind of year worth.

What can be done to protect us from the future ourselves ?

May it should break if any of this files are removed from this list?

**Comment by lipemorais** [comment]
... this kind of test* ...

**Comment by cuducos** [comment]
> May it should break if any of this files are removed from this list?

I don't think so, because we remove old versions when there are new ones available… although we wold never see the `len()` of the list get smaller, because we would either replace a file (adding a newer version) or add a new dataset (which was not present in the list before).

**Comment by lipemorais** [comment]
Why is this constant important for toolbox?

The LATEST constant is not used anywhere in this file, if I remove it all project tests will pass smoothly. 
Is it OK?

**Comment by cuducos** [comment]
It's [used here](https://github.com/datasciencebr/serenata-toolbox/blob/master/serenata_toolbox/datasets/__init__.py#L71-L800), in a function [documented here](https://github.com/datasciencebr/serenata-toolbox#example-2-using-shortcuts).

Maybe the test you'd like to enhance is [this one](https://github.com/datasciencebr/serenata-toolbox/blob/master/tests/test_datasets.py#L82-L850).

**Comment by lipemorais** [comment]
There is any point against enhance this tests?

**Comment by cuducos** [comment]
> Is there any point against enhance this tests?

Not at all ; )

**Pull request merged**
