### PR TITLE
Reinforce the need for version bumping

### PR DESCRIPTION
**Pull request by cuducos**
**What is the purpose of this Pull Request?**

The purpose of this PR is to reinforce the need for a version bump. Most _code reviews_ I've done lately ended up in this request, including one in which the contributor (wrongly) claimed that a version bump wasn't need for his PR. Beyond that the release failed a couple of times (maybe because of the lack of a version bump) and I had to send things to PyPI manually.

**What was done to achieve this purpose?**

Added a few lines in the `README.rst` not only reinforcing that a version bump is needed, but explaining why it's needed. 

**How to test if it really works?**

Read the `diff`, catch my typos, blame me, wait for my `Fix typos` commit, done.

**Who can help reviewing it?**

Anyone ; )

### CODE REVIEW

**Comment by lipemorais** [comment]
Look good to merge to me. :)

**Comment by giovanisleite** [comment]
I would suggest putting it with "**always**" on the pull request template too (over the "do not forget").

**Comment by cuducos** [comment]
Great idea, @giovanisleite — done in 0c34c21

**Comment by lipemorais** [comment]
I believe that this PR is ready to be merged.
@anaschwendler, could you help us with it?

**Comment by anaschwendler** [comment]
I think that is clear enough now to see that the version bump is really necessary, even in minor cases, that is why we have minor bumps :)

Great @cuducos

**Comment by cuducos** [comment]
> Great @cuducos

Is anything missing for a merge?

**Comment by anaschwendler** [comment]
No, I'll leave a last test check, and then I'll merge!

1. Clone the project
```console
$ git clone git@github.com:datasciencebr/serenata-toolbox.git
```

2. Change to Toolbox folde:
```console
$ cd serenata-toolbox
```

3. Change do @cuducos branch:
```console
$ git checkout -b cuducos-reinforce-the-need-for-version-bump origin/cuducos-reinforce-the-need-for-version-bump
```

4. Merge with the master:
```console
$ git merge master
```

5. Check the code locally, and it's fine!

**Pull request merged**
