### PR TITLE
Fixed missing pre formated tags

### PR DESCRIPTION
**Pull request by Zubru22**
I think those two tags should work now :)

### CODE REVIEW

**Comment by cuducos** [comment]
It's working beautifully @Zubru22 — many thanks 🎉 

I'd kindly ask you to include a version bump. It's really important for us (more details in the [last paragraphs of this section](https://github.com/datasciencebr/serenata-toolbox#contributing)). 

Just open `setup.py` and change `version='12.3.0'` by `version='12.3.1'` (as of today). Then commit, push to this branch and we're good to go ; )

**Comment by Zubru22** [comment]
Sorry, forgot to do it. It's done now, do I have to re-submit pull request? Or is it good to go?

**Comment by anaschwendler** [comment]
That is right @Zubru22, you're now good to go!

I'll wait for @cuducos merge the PR, since he started the review ;)

**Comment by cuducos** [comment]
Yay, many thanks @Zubru22 ; ) 

Just out of curiosity:

> do I have to re-submit pull request? Or is it good to go?

The PR is based on the branch you created in your fork (in this case `fix-readme`). So any commit pushed to that branch and fork would automagically pop in here ; )

**Pull request merged**
