### PR TITLE
Add PyPI label to README.rst

### PR DESCRIPTION
**Pull request by marius92mc**
**What is the purpose of this Pull Request?**
Fixes https://github.com/datasciencebr/serenata-toolbox/issues/148. 

**What was done to achieve this purpose?**
Add a URL to the mentioned label. 

**How to test if it really works?**
See README.rst.

### CODE REVIEW

**Comment by marius92mc** [comment]
Should this be merged in this state knowing the coverage remained at that rate, @giovanisleite?

**Comment by giovanisleite** [comment]
> Should this be merged in this state knowing the coverage remained at that rate, @giovanisleite?

Yes, the coverage and the travis error are not related to this issue.

I don't know if it is necessary to bump  the version, but @jtemporal can tell you.

**Comment by marius92mc** [comment]
Yeah, I also think it is not needed to bump the version.

**Comment by giovanisleite** [comment]
> Yeah we are trying to have a at least a minor bump version for any change in this project. :)

Actually, the readme/documentation is part of the project, so.. i think it is

**Comment by marius92mc** [comment]
Alright, @giovanisleite, I bumped the version.

**Comment by cuducos** [comment]
Regarding the version bump issue, it's written in the `README.md`:

> Always suggest a version bump.

Always. Because every new code merged into `master` triggers the CI. And then the CI [triggers a new release to PyPI](https://github.com/datasciencebr/serenata-toolbox/blob/master/.travis.yml#L15-L23). And this would ruin the whole project (omg I'm so dramatic…) hahaha… anyway, no, that's not a big big problem. But it's important to understand that not bumping the version will break something, and it's also important to understand why it breaks something.

So unless you [add `[skip ci]` to your commit message](https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build), yes, bumping version is required ; )

**Pull request merged**
