### PR TITLE
Increase travis ci waiting_time

### PR DESCRIPTION
**Pull request by lipemorais**
**What is the purpose of this Pull Request?**
Fix [broken builds on Travis Ci](https://travis-ci.org/datasciencebr/serenata-toolbox/builds)

**What was done to achieve this purpose?**
I increased travis_wait time to 30 minutes so it do not break if be 10 minutes without outuput .

**How to test if it really works?**
I have a already [green build](https://travis-ci.org/lipemorais/serenata-toolbox/builds/263643821) fixed by just this change

**Who can help reviewing it?**
@Irio @cuducos @jtemporal @anaschwendler could help with this PR.

[skip ci]

### CODE REVIEW

**Comment by cuducos** [comment]
@jtemporal If I merge it it will try to roll out a new version to PyPi. If I ask @lipemorais to add `[skip ci]` to the opening post of this PR we miss the chance to see if the waiting time added was enough… now that we actually see the green lights from the CI I think @lipemorais can add the tag so we merge it, right?

**Comment by lipemorais** [comment]
`[skip ci]` added. :)

**Comment by lipemorais** [comment]
Since [this build](https://travis-ci.org/datasciencebr/serenata-toolbox/builds/264895280) tell us that is take almost 20 minutes I changed it to 20 minutes instead of 30.

**Comment by jtemporal** [comment]
The thing is: most recent builds ran _without_ the 20 minutes tag and the builds were _successful_. I believe the problem was on the other end of the journey tests (gov APIs). I'm not sure we should merge this just yet.

Also, I'm looking for a way to only deploy when setup had a version bump. There must be a way to do so using the `condition` tag. Open to ideas on that matter.

**Comment by cuducos** [comment]
> most recent builds ran _without_ the 20 minutes tag

So can we close that without merging… or the _wait_ command is not such a burden?

**Comment by jtemporal** [comment]
>So can we close that without merging… or the wait command is not such a burden?

The build on #137 failed with a time warning. I'd like to wait on both PRs to finish building to check whether this one is necessary or can be closed.

cc @cuducos

**Comment by jtemporal** [comment]
It passes! 🎉 

Quick reminder: We need a version bump here!

**Comment by cuducos** [comment]
> Quick reminder: We need a version bump here!

Do we? We have `[ci skip]` in the opening comment… I must admit I'm kind o' lost

**Comment by lipemorais** [comment]
@jtemporal I agree that we don't need a version bump here.

**Comment by jtemporal** [comment]
@cuducos and @lipemorais we do need because the skip CI needs to be in the commit message to work.

Also I pretty much believe we are moving towards using patch bumps for everything documentation-wise as commented on #135

**Comment by lipemorais** [comment]
After 25 days we finally have a [green build](https://travis-ci.org/datasciencebr/serenata-toolbox/builds/270850966)!

**Pull request merged**
