### PR TITLE
Send related databases info - json pattern

### PR DESCRIPTION
**Pull request by juscilan**
Database containing .json format addresses

### CODE REVIEW

**Comment by cuducos** [comment]
Status: @Irio will check this data, probably in a notebook in the main repo, and afterwards we decide how to proceed with this PR ; )

**Comment by jtemporal** [comment]
Hi all, quick question here: Why isn't all of the addresses condensed in one single big json file?

**Comment by jtemporal** [comment]
Also, shouldn't this be a compressed file uploaded to our S3 instead of **70 files** inside the toolbox?

**Comment by cuducos** [comment]
Closed by inactivity.

**Pull request closed without merging**
