### PR TITLE
Add donation badge

### PR DESCRIPTION
**Pull request by subkrish**
Issue #151 

This is just a template to help you make your point clear with this PR. :)

**What is the purpose of this Pull Request?**
This PR adds a donation badge to the README page.

**What was done to achieve this purpose?**
A badge was added similar to how other badges have been added in the README file.

**How to test if it really works?**
It can be clicked and if redirects to the right page this means it works.

### CODE REVIEW

**Comment by subkrish** [comment]
I do not know what the problem with Travis-CI is. Can someone tell why it has not passed?

**Comment by giovanisleite** [comment]
It is not related to your PR, @subkrish.

**Comment by cuducos** [comment]
Hi @subkrish — don't worry about Travis, our tests depend on very unstable (governmental) external services (take a look in #146 if you're interested in this discussion).

Anyway I cannot merge your PR because as stated in the `README.md` we **always** need a _version bump_. Not always… is your commit has `[skip ci]` in the commit message (which is not the case) — more on that [here](https://github.com/datasciencebr/serenata-toolbox/pull/149#issuecomment-333606216).

So either you have to add a version bump (just edit `setup.py` with a patch version bump) or amend your commit with `[skip ci]`, ok?

**Comment by subkrish** [comment]
@cuducos Made the change. I updated the commit by adding the version bump as suggested in the `README`. Thanks!

**Comment by cuducos** [comment]
Yay, thanks @subkrish ; )

**Pull request merged**
