### PR TITLE
Add dataset with OCR from receipts

### PR DESCRIPTION
**Pull request by cuducos**
Thanks @fgrehm ; )

### CODE REVIEW

**Comment by cuducos** [comment]
@jtemporal Would you mind helping me in settings the correct version?

**Comment by jtemporal** [comment]
Yes! 🎉 

Referring to [#34#issuecomment-290125435](https://github.com/datasciencebr/serenata-toolbox/issues/34#issuecomment-290125435) datasets additions are **minor** changes, (`major.minor.micro`) o/

**Comment by cuducos** [comment]
I committed a version bump, but it depends on 515afde from #38

**Comment by jtemporal** [comment]
@cuducos do you think we can change versions?

Include this bump to a earlier version (7.6.1) so that we can get this one merged while #38 is still under review? what do you think?

**Comment by cuducos** [comment]
Done!

**Pull request merged**
