### PR TITLE
Fix float convertion

### PR DESCRIPTION
**Pull request by cuducos**
This fixes a `float` conversion that was passing unnoticed and [breaking Rosie](https://github.com/datasciencebr/rosie/issues/77).

This is how I tested it.

In the toolbox environment:

1. Changed to (or create) `cuducos-fix-float-convertion` branch
2. Pull the commits from this PR

In Rosie's environment:

1. Uninstalled the current version of the toolbox: `$ pip uninstall serenata_toolbox`
2. Install my local toolbox instead: `$ pip install -e <path to serenata_toolbox>`
3. Run Rosie: `$ python rosie.py run chamber_of_deputies ../serenata-de-amor/research/data`

**Important**: I'm not sure this PR is really working, I believe it is because it goes further the point @jtemporal reported, however it throws an error typical of memory error… so I can't be sure.

### CODE REVIEW

**Comment by jtemporal** [comment]
@cuducos This looks good! version bump?

**Comment by cuducos** [comment]
I've done it in bf526ff but something got into `master` first. So… d03bc6b

**Comment by cuducos** [comment]
Regarding the error I got it's [this error](https://github.com/datasciencebr/rosie/issues/25). And this is the status of my hardware moments before crashing:

untitled

**Comment by cuducos** [comment]
Closed in favor of #144

**Pull request closed without merging**
